### ISSUE TITLE
Throwing an error when trying to start server

### ISSUE THREAD

**Issue by thinkholic** [thinkholic/backdrop-js#28]
Platform: MacOS
Version: v1.0.0-alpha.0
NPM Version: 6.14.9
Node.js Version: v14.15.3

### Steps to reproduce
1. Download v1.0.0-alpha.0 (Using CLI)
2. Install dependencies (Using CLI -i flag)
3. Run `npm run start:dev`

```
[nodemon] 2.0.12
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): *.*
[nodemon] watching extensions: js,mjs,json
[nodemon] starting `babel-node ./src/bin/www.js`
internal/modules/cjs/loader.js:883
  throw err;
  ^

Error: Cannot find module '../handlers/core/users'
Require stack:
- /<path>/src/routes/core.js
- /<path>/src/index.js
- /<path>/src/bin/www.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/<path>/src/routes/core.js:8:1)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Module._compile (/<path>/node_modules/pirates/lib/index.js:99:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Object.newLoader [as .js] (/<path>/node_modules/pirates/lib/index.js:104:7)
    at Module.load (internal/modules/cjs/loader.js:928:32) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/<path>/src/routes/core.js',
    '/<path>/src/index.js',
    '/<path>/src/bin/www.js'
  ]
}
[nodemon] app crashed - waiting for file changes before starting...
```

**Comment by thinkholic** [comment]
It seems this issue only occurring when using the CLI
