### ISSUE TITLE
`npm start:server` fails at first run after clonining

### ISSUE THREAD

**Issue by thinkholic** [thinkholic/backdrop-js#33]
#### Platform: MacOS
Version: v1.0.0-alpha.0
NPM Version: 6.14.9
Node.js Version: v14.15.3

#### Steps to reproduce

- Clone the app
- Run `yarn` in root directory
- Create `.env` from `.env.example` (in packages/server-nodejs)
- Run `yarn start:server`

```
internal/modules/cjs/loader.js:311
      throw err;
      ^

Error: Cannot find module '/<path>/backdrop-js/node_modules/@jetlab/jsondb/dist/index.js'. Please verify that the package.json has a valid "main" entry
    at tryPackage (internal/modules/cjs/loader.js:303:19)
    at Function.Module._findPath (internal/modules/cjs/loader.js:516:18)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:867:27)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/<path>/backdrop-js/packages/server-nodejs/src/utils/database/jsondb.js:1:1)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Module._compile (/<path>/backdrop-js/node_modules/pirates/lib/index.js:99:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:1092:10) {
  code: 'MODULE_NOT_FOUND',
  path: '/<path>/backdrop-js/node_modules/@jetlab/jsondb/package.json',
  requestPath: '@jetlab/jsondb'
```

**Comment by thinkholic** [comment]
Should fix with https://github.com/thinkholic/backdrop-js/commit/b4096db36f6d1f0902c7c65b03b5ff7e98e1c4cf
